# platform :ios, '9.0'
use_frameworks!

# Development Pods
target 'SmartCalling_Example' do

    pod 'SmartCallingSDK', :path => '../'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'

end

target 'SmartCallingCallKitProvider' do

    pod 'SmartCallingSDK', :path => '../'

end
